### ISSUE TITLE
test_processing unit tests should check its results

### ISSUE THREAD

**Issue by tankefugl** [emlynjdavies/PySilCam#13]
The test_processing unit tests presently generates plots and csv files and successfully checks that these are in place. However, the contents of the csv file (the result of the processing) is not checked.

Adding an explicit check to the results of the processing would improve the test substantially.

**Comment by emlynjdavies** [comment]
line 120-130 of test_process checks the contents of the STATS file

There are also checks that the h5 files exist.

Then later silcam_report will use both the STATS.csv and h5 files to generate the summary figure.

**Comment by tankefugl** [comment]
Ah, then I missed that! Then this can probably be closed.
